### ISSUE TITLE
Some confuse with patch generation and instances sampling

### ISSUE THREAD

**Issue by DeeperCS** [znck/mitosis-detection#1]
Hi, Rahul Kadyan, I'm so glad that I found such a great project you shared. I guess I read the same paper of your excellent implementation and I'm very curious about how to implement the details in a efficient way. Your code is pretty clear and easy to understand, however, I got some little questions when I read it as the list below:

In this function:

```
def patch_at(image, x, y, size=(101, 101)):
    x_start = x + size[0] / 2
    y_start = y + size[1] / 2
    x_end = x_start + size[0]
    y_end = y_start + size[1]
    p = image[:, x_start:x_end, y_start:y_end]
    return p
```

I think this episode is try to crop a patch from [x+50,y+50] to [x+151, y+151], why not treat the (x,y) as the center pixel of the patch?

Besides, in runner.py , line 152

```
for X_train, Y_train in batch:
            outputs = model.predict(X_train, batch_size=arguments.mini_batch, verbose=1)
            # Multiply each window with it's prediction and then pass it to the next layer
            for i in range(len(outputs)):
                X_train[i] = np.dot(X_train[i], outputs[i][0])
```

I'm got some confuse with 'Multiply each window with it's prediction'? As the paper says, 'The remaining is sampled from non-mitosis pixels by assigning to each pixel p a weight D(p)', I thought it should sampling by treat the prediction as a weight.

**Comment by znck** [comment]
Patch is centered at (x, y) in the original image. The `image` has a border of 101 pixels on each side (as many mitotic pixels are near boundary; border is created by mirroring image). Though 50-pixel border is enough but for simplicity, I chose border of 101-pixel width.

And second part (`line 152`) is wrong. I am working on it (with @achaar).

P.S. I have made a lot of changes in last few hours.

**Comment by DeeperCS** [comment]
Thanks for you reply. I think It's really cool and I'm wondering if I could be involved in this fantastic project, it's so attractive to me, I wish I could make some contributions~

**Comment by znck** [comment]
:+1: Sure! Do contribute. Happy to see you around.
